NumPy is a powerful library for scientific computing in Python that provides a multidimensional array object and a wide range of tools for working with these arrays. It is widely used in fields such as data analysis, machine learning, and scientific computing. In this article, we will be discussing NumPy functions in Python, which are essential for the efficient and effective manipulation of NumPy arrays.

**What are Numpy Functions in Python?**

NumPy functions are built-in functions provided by the NumPy library that operate on NumPy arrays. These functions are designed to efficiently process large amounts of data and perform complex calculations on multidimensional arrays. NumPy functions are designed to work with NumPy arrays and offer superior performance compared to traditional Python functions.

**Syntax of Numpy Functions in Python**

The syntax of NumPy functions in Python typically follows the following structure:

**numpy.function_name(array, parameters)**

where "function_name" is the name of the NumPy function, "array" is the NumPy array on which the function is to be applied, and "parameters" are any additional parameters required by the function.

**Parameters of Numpy Functions in Python**


NumPy functions in Python take one or more arrays as input and can also accept additional parameters that modify their behavior. The parameters of NumPy functions depend on the specific function being used. Here are some common parameters:

**axis:** This parameter specifies the axis along which the function is applied. It is an optional parameter and its default value is None. If axis is set to None, the function will be applied to the entire array.

**dtype:** This parameter specifies the data type of the returned array. It is an optional parameter and its default value is None. If dtype is set to None, the data type of the returned array will be the same as the input array.

**out:** This parameter specifies the output array where the result of the function will be stored. It is an optional parameter and its default value is None. If out is set to None, the function will create a new array to store the result.

**keepdims:** This parameter specifies whether to keep the dimensions of the input array in the output array. It is an optional parameter and its default value is False. If keepdims is set to True, the dimensions of the output array will be the same as the input array. If keepdims is set to False, the dimensions of the output array will be reduced by one.

**Return Value of Numpy Functions in Python**

The return value of a NumPy function in Python depends on the specific function being used. Some NumPy functions return a new array with the calculated results, while others modify the original array in place. However, some NumPy functions have optional output parameters such as the ‘out’ parameter. These functions allow you to specify an output array where the result will be stored. In this case, the return value will be a reference to the output array rather than a new array.


PREPBYTES
MARCH 2, 2023
Last Updated on March 2, 2023 by Prepbytes



NumPy is a powerful library for scientific computing in Python that provides a multidimensional array object and a wide range of tools for working with these arrays. It is widely used in fields such as data analysis, machine learning, and scientific computing. In this article, we will be discussing NumPy functions in Python, which are essential for the efficient and effective manipulation of NumPy arrays.

What are Numpy Functions in Python?
NumPy functions are built-in functions provided by the NumPy library that operate on NumPy arrays. These functions are designed to efficiently process large amounts of data and perform complex calculations on multidimensional arrays. NumPy functions are designed to work with NumPy arrays and offer superior performance compared to traditional Python functions.

Syntax of Numpy Functions in Python
The syntax of NumPy functions in Python typically follows the following structure:

numpy.function_name(array, parameters)
where "function_name" is the name of the NumPy function, "array" is the NumPy array on which the function is to be applied, and "parameters" are any additional parameters required by the function.

Parameters of Numpy Functions in Python
NumPy functions in Python take one or more arrays as input and can also accept additional parameters that modify their behavior. The parameters of NumPy functions depend on the specific function being used. Here are some common parameters:

axis: This parameter specifies the axis along which the function is applied. It is an optional parameter and its default value is None. If axis is set to None, the function will be applied to the entire array.
dtype: This parameter specifies the data type of the returned array. It is an optional parameter and its default value is None. If dtype is set to None, the data type of the returned array will be the same as the input array.
out: This parameter specifies the output array where the result of the function will be stored. It is an optional parameter and its default value is None. If out is set to None, the function will create a new array to store the result.
keepdims: This parameter specifies whether to keep the dimensions of the input array in the output array. It is an optional parameter and its default value is False. If keepdims is set to True, the dimensions of the output array will be the same as the input array. If keepdims is set to False, the dimensions of the output array will be reduced by one.
Return Value of Numpy Functions in Python
The return value of a NumPy function in Python depends on the specific function being used. Some NumPy functions return a new array with the calculated results, while others modify the original array in place. However, some NumPy functions have optional output parameters such as the ‘out’ parameter. These functions allow you to specify an output array where the result will be stored. In this case, the return value will be a reference to the output array rather than a new array.

**Important Numpy Functions in Python**

Here are some of the important NumPy functions in Python which every Data scientist must know:

1. np.array(): This function is used to create an array in NumPy.

In [ ]:
import numpy as np
b=[1,2,3]
print(type(b))
arr=np.array([1,2,3])
print(arr)
print(type(arr))

<class 'list'>
[1 2 3]
<class 'numpy.ndarray'>


2. np.arange(): This function is used to create an array with a range of values.

In [ ]:
arr=np.arange(2,10)
print(arr)
print(type(arr))

[2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


3. np.zeros(): This function is used to create an array filled with zeros.

In [ ]:
arr = np.zeros(3)
print(arr)

[0. 0. 0.]


4. np.ones(): This function is used to create an array filled with ones.



In [ ]:
arr = np.ones(3)
print(arr)

[1. 1. 1.]


5. np.linspace(): This function is used to create an array with a specified number of evenly spaced values.

In [ ]:
arr = np.linspace(0, 1, 5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


6. np.random.rand(): This function is used to create an array with random values between 0 and 1.

In [ ]:
arr = np.random.rand(3)
print(arr)

[0.56844173 0.50193956 0.70673092]


7. np.random.randint(): This function is used to create an array with random integer values between a specified range.

In [ ]:
arr = np.random.randint(0, 10, 5)
print(arr)

[2 3 3 2 7]


8. np.max(): This function is used to find the maximum value in an array.

In [ ]:
arr = np.array([1, 2, 3])
max_value = np.max(arr)
print(max_value)

3


9. np.min(): This function is used to find the minimum value in an array.

In [ ]:
arr = np.array([1, 2, 3])
min_value = np.min(arr)
print(min_value)

1


10. np.mean(): This function is used to find the mean value of an array.

In [ ]:
arr = np.array([1, 2, 3])
mean_value = np.mean(arr)
print(mean_value)

2.0


11. np.median(): This function is used to find the median value of an array.

In [ ]:
arr = np.array([1, 2, 3])
median_value = np.median(arr)
print(median_value)

2.0


12. np.dot(): This function is used to find the dot product of two arrays.

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

dot_product = np.dot(arr1, arr2)
print(dot_product)

32


In [ ]:
import numpy as np
arr = np.array([0, 30, 60, 90, 120, 150, 180])
print("\nThe sin value of the angles",end = " ")
print(np.sin(arr * np.pi/180))
print("\nThe cosine value of the angles",end = " ")
print(np.cos(arr * np.pi/180))
print("\nThe tangent value of the angles",end = " ")
print(np.tan(arr * np.pi/180))



The sin value of the angles [0.00000000e+00 5.00000000e-01 8.66025404e-01 1.00000000e+00
 8.66025404e-01 5.00000000e-01 1.22464680e-16]

The cosine value of the angles [ 1.00000000e+00  8.66025404e-01  5.00000000e-01  6.12323400e-17
 -5.00000000e-01 -8.66025404e-01 -1.00000000e+00]

The tangent value of the angles [ 0.00000000e+00  5.77350269e-01  1.73205081e+00  1.63312394e+16
 -1.73205081e+00 -5.77350269e-01 -1.22464680e-16]


In [ ]:
import numpy as np
arr = np.array([12.202, 90.9, -123.020, 23.202])
print(np.floor(arr))

[  12.   90. -124.   23.]


** Shape of an Array**

The .shape attribute of a Numpy array returns a tuple representing the dimensions of the array. It is crucial for understanding the structure of the array, whether it is one-dimensional (1D), two-dimensional (2D), or higher-dimensional.

In [ ]:
import numpy as np

array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape of array:", array_2d.shape)


Shape of array: (2, 3)


**Dimensionality**

The .ndim attribute provides the number of dimensions of the array, offering insight into the complexity and potential uses of the array in operations such as matrix multiplication or reshaping.

In [ ]:
print("Number of dimensions:", array_2d.ndim)


Number of dimensions: 2


**Data Type of the Array Elements**

The .dtype attribute indicates the data type of the elements in the array, such as int32, float64, etc. This information is crucial for memory management and for performing type-appropriate operations on array elements.

In [ ]:
print("Data type of array elements:", array_2d.dtype)


Data type of array elements: int64


**Size of the Array**


The .size attribute returns the total number of elements in the array. This attribute is particularly useful in loops and when performing operations that require knowledge of the array's total element count.

In [ ]:
print("Total number of elements:", array_2d.size)


Total number of elements: 6


**Item Size**

The .itemsize attribute returns the size (in bytes) of each array element. This is directly tied to the array's data type and is vital for understanding the memory consumption of an array.

In [ ]:
print("Size of each element in bytes:", array_2d.itemsize)


Size of each element in bytes: 8
